import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';

/**
 * API endpoint to scan for newly generated images in real-time
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { folderId } = body;
    
    const publicDir = path.join(process.cwd(), 'public');
    const generatedImages: string[] = [];
    
    try {
      const files = await fs.readdir(publicDir);
      
      // Look for images generated by the ComfyUI script
      const imageFiles = files.filter(file => {
        const isImage = /\.(png|jpg|jpeg|gif|webp)$/i.test(file);
        const isGenerated = file.includes('prompt_engineer_image_') || 
                           file.includes('generated_image') ||
                           file.includes('ComfyUI');
        return isImage && isGenerated;
      });
      
      // Sort by filename to maintain order (prompt_engineer_image_1, 2, 3, etc.)
      imageFiles.sort((a, b) => {
        const aMatch = a.match(/prompt_engineer_image_(\d+)/);
        const bMatch = b.match(/prompt_engineer_image_(\d+)/);
        
        if (aMatch && bMatch) {
          return parseInt(aMatch[1]) - parseInt(bMatch[1]);
        }
        
        return a.localeCompare(b);
      });
      
      for (const file of imageFiles) {
        // Return relative path for web access
        generatedImages.push(`/${file}`);
      }
      
      return NextResponse.json({
        success: true,
        images: generatedImages,
        count: generatedImages.length,
        timestamp: new Date().toISOString()
      });
      
    } catch (error) {
      console.error('❌ Error scanning for generated images:', error);
      return NextResponse.json({
        success: false,
        images: [],
        count: 0,
        error: error instanceof Error ? error.message : 'Unknown error'
      });
    }
    
  } catch (error: unknown) {
    console.error('Error in scan-generated-images endpoint:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred';
    return NextResponse.json({
      success: false,
      error: errorMessage
    }, { status: 500 });
  }
}

/**
 * GET endpoint for testing the image scanning service
 */
export async function GET() {
  try {
    const publicDir = path.join(process.cwd(), 'public');
    
    return NextResponse.json({
      success: true,
      service: 'Image Scanning Service',
      status: 'Ready',
      publicDirectory: publicDir,
      description: 'Scans for newly generated images in real-time'
    });
    
  } catch (error: unknown) {
    console.error('Error in scan-generated-images GET endpoint:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred';
    return NextResponse.json({
      error: errorMessage
    }, { status: 500 });
  }
}